include: package:pedantic/analysis_options.yaml

linter:
  rules:
    ## UI-as-Code
    prefer_spread_collections: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_for_elements_to_map_fromIterable: true

analyzer:
  exclude:
    - lib/**/messages/*.dart
    - lib/**/*.g.dart
